######################
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.4 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode -constantSTAR 0.119
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.4 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.4 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode -correctSTAR
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.4 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode -boxDirEffect
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.4 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode -boxDirEffect -correctSTAR
#
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.3 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode -constantSTAR 0.119
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.3 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.3 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode -correctSTAR
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.3 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode -boxDirEffect
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.3 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode -boxDirEffect -correctSTAR
#
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.2 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode -constantSTAR 0.119
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.2 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.2 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode -correctSTAR
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.2 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode -boxDirEffect
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.2 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode -boxDirEffect -correctSTAR
#
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.1 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode -constantSTAR 0.119
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.1 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.1 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode -correctSTAR
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.1 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode -boxDirEffect
./lig-radiation -iter 20 -metafile MetaFile.txt -voxelspace VoxelSpace.txt -outputAll -phprodfile Radiation/9-week-result/NumP1-TL-MP-12-2-2012.dat -Voxbox 0.1 -numParts 1 -treeLocations Radiation/TL-MP-12-2-2012.dat -inputTree Radiation/Puut/this9-1-2-10.xml -radMethod 3 -targetTreeRad 0.5 -appendMode -boxDirEffect -correctSTAR
